-- Migration 039: Threaded Inbox
--
-- Adds two things:
--   1. conversation_token on messages — a UUID that acts as the client's
--      secret access key to view and continue their thread without an account.
--   2. message_replies table — stores every subsequent exchange (expert and
--      client) after the original paid message.
--
-- The token is auto-generated by the DB DEFAULT for all new AND existing rows.

-- ── 1. Add conversation_token to messages ────────────────────────────────────
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS conversation_token UUID UNIQUE DEFAULT gen_random_uuid();

-- Make non-nullable (all rows got a value from the DEFAULT above)
ALTER TABLE public.messages
  ALTER COLUMN conversation_token SET NOT NULL;

-- Fast lookup by token (used by public edge functions)
CREATE INDEX IF NOT EXISTS idx_messages_conversation_token
  ON public.messages(conversation_token);

-- ── 2. Create message_replies ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.message_replies (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id  UUID        NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  -- 'expert' = creator; 'client' = the person who paid
  sender_type TEXT        NOT NULL CHECK (sender_type IN ('expert', 'client')),
  content     TEXT        NOT NULL CHECK (char_length(content) BETWEEN 1 AND 5000),
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_message_replies_message_id
  ON public.message_replies(message_id);

-- ── 3. RLS ───────────────────────────────────────────────────────────────────
ALTER TABLE public.message_replies ENABLE ROW LEVEL SECURITY;

-- Authenticated experts can read replies to their own messages
CREATE POLICY "Creators can read replies to their messages"
  ON public.message_replies FOR SELECT
  TO authenticated
  USING (
    message_id IN (
      SELECT m.id FROM public.messages m
      WHERE m.creator_id IN (
        SELECT c.id FROM public.creators c WHERE c.user_id = auth.uid()
      )
    )
  );

-- Authenticated experts can insert expert-side replies (service role also bypasses RLS)
CREATE POLICY "Creators can insert expert replies"
  ON public.message_replies FOR INSERT
  TO authenticated
  WITH CHECK (
    sender_type = 'expert' AND
    message_id IN (
      SELECT m.id FROM public.messages m
      WHERE m.creator_id IN (
        SELECT c.id FROM public.creators c WHERE c.user_id = auth.uid()
      )
    )
  );
